Repository Hiviexd/tournament-tracker, pull requests merged in 2025-03, with the labels that each got.

#19 articles system
  .eslintrc.cjs
  interfaces/Article.ts
  interfaces/Log.ts
  package.json
  server/app.ts
  server/controllers/ArticlesController.ts
  server/models/articleModel.ts
  server/routers/articlesRouter.ts
  server/routers/authRouter.ts
  server/routers/logsRouter.ts
  server/routers/ticketsRouter.ts
  server/routers/tournamentsRouter.ts
  server/routers/usersRouter.ts
  server/routers/votingsRouter.ts
  src/api/articles.ts
  src/base/header.config.ts
  src/base/routes.config.tsx
  src/components/logs/LogsFilters.tsx
  src/hooks/useArticle.ts
  src/pages/ArticlePage.tsx
  src/pages/CreateArticlePage.tsx
  src/pages/DocumentationListPage.tsx
  src/themes/icons.ts
  yarn.lock
Labels: size/XL

#23 Allow read-only access to non loggedin users
  server/controllers/ArticlesController.ts
  server/controllers/TicketsController.ts
  server/controllers/VotingsController.ts
  server/middlewares/auth.ts
  server/routers/articlesRouter.ts
  server/routers/logsRouter.ts
  server/routers/ticketsRouter.ts
  server/routers/tournamentsRouter.ts
  server/routers/usersRouter.ts
  server/routers/votingsRouter.ts
  server/services/TicketService.ts
  src/api/articles.ts
  src/base/header.config.ts
  src/base/routes.config.tsx
  src/components/common/Header.tsx
  src/components/common/header/MainNavigation.tsx
  src/components/tickets/TicketMessages.tsx
  src/components/tickets/TicketsFilters.tsx
  src/components/votings/VotingFilters.tsx
  src/pages/HomePage.tsx
  src/pages/TicketDetailsPage.tsx
  src/pages/VotingListPage.tsx
Labels: size/L

#27 add assets previewer tool
  interfaces/OsuApi.ts
  package.json
  public/assets/default-banner.jpg
  public/assets/default-bg.jpg
  server/constants/seo.config.ts
  server/controllers/UsersController.ts
  server/routers/usersRouter.ts
  src/api/users.ts
  src/base/header.config.ts
  src/base/routes.config.tsx
  src/components/common/SignInBanner.tsx
  src/components/previewer/BadgesTab.tsx
  src/components/previewer/InGameBannersTab.tsx
  src/components/previewer/NewsBannersTab.tsx
  src/components/tickets/ReportForm.tsx
  src/components/tickets/TicketForm.tsx
  src/hooks/useBadgePreviewer.ts
  src/hooks/useUsers.ts
  src/pages/AssetsPreviewerPage.tsx
  src/sass/app.scss
  src/sass/components/BadgesTab.scss
  src/sass/components/InGameBannersTab.scss
  src/sass/components/NewsBannersTab.scss
  src/themes/icons.ts
  yarn.lock
Labels: size/XXL

#28 Add mappool compliance tool
  interfaces/OsuApi.ts
  package.json
  server/app.ts
  server/constants/artist-permissions/bannedSources.json
  server/constants/artist-permissions/flagged.json
  server/constants/artist-permissions/overrides.json
  server/controllers/BeatmapsController.ts
  server/helpers/index.ts
  server/middlewares/rateLimiter.ts
  server/routers/beatmapsRouter.ts
  server/services/BeatmapService.ts
  server/services/OsuApiService.ts
  server/services/OsuBotService.ts
  src/api/beatmaps.ts
  src/base/header.config.ts
  src/base/routes.config.tsx
  src/components/compliance/BeatmapCard.tsx
  src/components/compliance/ResultSection.tsx
  src/hooks/useBeatmaps.ts
  src/pages/HomePage.tsx
  src/pages/MappoolCompliancePage.tsx
  src/sass/app.scss
  src/sass/components/BeatmapCard.scss
  src/themes/icons.ts
  src/themes/main.ts
  yarn.lock
Labels: new feature, size/XXL

#31 Fix matadata typo in `Compliance Checker`
  src/components/compliance/BeatmapCard.tsx
Labels: size/XS

#32 Update ak+q and overrides
  server/constants/artist-permissions/flagged.json
  server/constants/artist-permissions/overrides.json
Labels: improvement, size/L
